config/routes.rb
RailsApp::Application.routes.draw do
  resources :users
  resources :sessions, only: [:new, :create, :destroy]
  
  root 'static_pages#home'
  get '/help'    => 'static_pages#help'
  get '/about'   => 'static_pages#about'
  get '/contact' => 'static_pages#contact'

  match '/signup',  to: 'users#new',            via: 'get'
  match '/signin',  to: 'sessions#new',         via: 'get'
  match '/signout', to: 'sessions#destroy',     via: 'delete'
  

end

app/models/user.rb
class User < ActiveRecord::Base
  VALID_EMAIL_REGEX = /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\z/i

  before_save { |user| user.email = user.email.downcase}
  before_create :create_remember_token
  has_secure_password

  validates :name, presence: true, length: { maximum: 50 }
  validates :email, presence: true, format: { with: VALID_EMAIL_REGEX},
            uniqueness: {case_sensitive: false}
  validates :password, length: { minimum: 6 }         

  def User.new_remember_token
    SecureRandom.urlsafe_base64
  end

  def User.hash(token)
    Digest::SHA1.hexdigest(token.to_s)
  end
  private
    def create_remember_token
        self.remember_token = User.hash(User.new_remember_token)
      end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  include SessionsHelper
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
	def new
		
	end

	def create
		user = User.where(email: params[:sessions][:email].downcase).first
		if user && user.authenticate(params[:sessions][:password])
			sign_in user
			redirect_back_or user
		else
			flash.now[:danger] = 'Invalid email/password'
			render 'new'
		end
	end

	def destroy
		sign_out
		redirect_to root_path
	end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end

  def help
  end

  def about
  end

  def contact
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :signed_in_user, only: [:index, :edit, :update]
  before_action :correct_user,   only: [:edit, :update]
  before_action :admin_user,     only: :destroy

  def index
    per_page = 10
    @users = User.paginate page: params[:page], per_page: per_page
    @part = render_to_string(:partial => "users/list",:layout => false, :locals => { :users => @users })

    respond_to do |format|
      format.json { render :json => { :partial => @part } }
      format.html
    end
  end

  def show
    @user = User.find params[:id]
  end
 
  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      sign_in @user
      flash[:success] = "Bienvenido a la aplicacion"
      redirect_to @user
    else
      render "new"
    end
  end

  def edit
  end

  def update
    if @user.update_attributes(user_params)
      sign_in @user
      flash[:success] = "Profile updated"
      redirect_to @user
    else
      render "edit"
    end
  end

  def destroy
    User.find(params[:id]).destroy
    flash[:success] = "User deleted."
    redirect_to users_url
  end

  private
    def user_params
      params.require(:user).permit(:name, :email, :password, 
                      :password_confirmation)
    end

    def signed_in_user
      unless signed_in?
        store_location
        redirect_to signin_path, notice: 'Please sign in'
      end
    end

    def correct_user
      @user = User.find(params[:id])
      redirect_to root_path unless current_user?(@user)
    end

    def admin_user
      redirect_to(root_url) unless current_user.admin?
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
	def full_title(page_title)
		base_title = 'Aplicacion de pruebas'
		if page_title.empty?
			base_title
		else
			"#{base_title} | #{page_title}"
		end
	end
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def sign_in(user)
    #sign in user
    remember_token = User.new_remember_token
    cookies.permanent[:remember_token] = remember_token
    user.update_attribute(:remember_token, User.hash(remember_token))
    self.current_user = user
  end

  def signed_in?
    !current_user.nil?
  end

  def current_user=(user)
    @current_user = user
  end

  def current_user
    remember_token = User.hash(cookies[:remember_token])
    @current_user ||= User.find_by(remember_token: remember_token)
  end

  def current_user?(user)
    user == current_user
  end

  def sign_out
    self.current_user = nil
    cookies.delete :remember_token
  end

  def redirect_back_or(default)
    redirect_to(session[:return_to] || default)
    session.delete(:return_to)
  end

  def store_location
    session[:return_to] = request.url if request.get?
  end

end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper

	def gravatar_for(user, options = { size: 50 })
		gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
		size = options[:size]
		gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}?s=#{size}"
		image_tag(gravatar_url, alt: user.name, class: "gravatar")
	end
end

app/views/layouts/_footer.html.erb
<footer>
	<small>Ejemplo by @misterpan</small>
	<nav>
		<ul>
			<li><%= link_to "About", about_path %></li>
			<li><%= link_to "Contact", contact_path %></li>
			<li><%= link_to "News", '#' %></li>
		</ul>
	</nav>
</footer>

app/views/layouts/_header.html.erb
<nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
	<div class="container">
		<div class="navbar-inner">
			<%= link_to "Pagina de prueba", root_path, id: 'logo' %>
			<ul class="nav navbar-nav navbar-right">
				<li><%= link_to 'Home', root_path %></li>
				<li><%= link_to 'Help', help_path %></li>
				<% if signed_in? %>
				<li><%= link_to "Users", users_path %></li>
	            <li id="fat-menu" class="dropdown">
	              <a href="#" class="dropdown-toggle" data-toggle="dropdown">
	                Cuenta <b class="caret"></b>
	              </a>
	              <ul class="dropdown-menu">
	                <li><%= link_to "Profile", current_user %></li>
	                <li><%= link_to "Settings", edit_user_path(current_user) %></li>
	                <li class="divider"></li>
	                <li>
	                  <%= link_to "Salir", signout_path, method: "delete" %>
	                </li>
	              </ul>
	            </li>
				<% else %>
				<li><%= link_to 'Ingresar', signin_path %></li>
				<% end %>
			</ul>
		</div>
	</div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
	<html>
	<head>
	  <title><%= full_title(yield(:title)) %></title>
	  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
	  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
	  <%= csrf_meta_tags %>
	</head>
	<body>
		<%= render "layouts/header" %>
		<div class="container">
			<% flash.each do |key, value| %>
				<%= content_tag(:div, value, class: "alert alert-#{key}") %>
			<% end %>
			<%= yield %>
			<%= render "layouts/footer" %>
			<%= debug params if Rails.env.development? %>
			<%#= debug request if Rails.env.development? %>
		</div>
	</body>
</html>

app/views/shared/_error_messages.html.erb
<% if @user.errors.any? %>
	<div id="">
		<%= content_tag(:div, "The form contains #{pluralize(@user.errors.count, "error")}", class: "alert alert-danger") %>

		<!-- <ul>
			<% @user.errors.full_messages.each do |msg| %>
			<li class="text-danger"><%=msg %></li>
			<% end %>
		</ul> -->
	</div>

<% end %>

app/views/static_pages/about.html.erb
<% provide :title, 'Acerca' %>
<h1>Pagina de acerca</h1>
<p>Find me in app/views/static_pages/about.html.erb</p>

app/views/static_pages/contact.html.erb
<% provide :title, 'Contacto' %>
<h1>Pagina de contacto</h1>
<p>Find me in app/views/static_pages/contact.html.erb</p>

app/views/static_pages/help.html.erb
<% provide :title, 'Ayuda' %>
<h1>Pagina de ayuda</h1>
<p>Find me in app/views/static_pages/home.html.erb</p>

app/views/static_pages/home.html.erb
<div class="center jumbotron">
	<h1>Bienvenido a la pagina de prueba</h1>
	<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod
	tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam</p>
	<%= link_to "Sign up", 'signup', class: "btn btn-large btn-primary" %>
</div>

<%= link_to image_tag("http://rubyonrails.org/images/rails.png", alt: 'logo'), 'http://rubyonrails.org'  %>

app/views/users/_list.html.erb
<%= will_paginate  %>
<ul class="users">
  <% @users.each do |user| %>
    <li>
      <%= gravatar_for user, size: 52 %>
      <%= link_to user.name, user %>
      <% if current_user.admin? && !current_user?(user) %>
	    | <%= link_to "delete", user, method: :delete,
	                                  data: { confirm: "You sure?" } %>
	  <% end %>
    </li>
  <% end %>
</ul>
<%= will_paginate %>

app/views/users/edit.html.erb
<% provide :title, 'Edit user'%>
<h1>Update your profile</h1>

<div class="row">
	<div class="col-md-6 col-md-offset-3">
		<%= render 'shared/error_messages' %>
		<%= form_for(@user, html: { class: "", role: "form" }) do |f| %>
			<div class="form-group">
				<%= f.label :name, class: "control-label" %>
				<%= f.text_field :name, class: "form-control" %>
				<% if @user.errors[:name] %>
					<% @user.errors[:name].each do |error| %>
						<span class="help-inline text-danger">- Name <%= error %></span><br>
					<% end %>
				<% end %>
			</div>
			
			<div class="form-group">
				<%= f.label :email, class: "control-label" %>
				<%= f.text_field :email, class: "form-control" %>
				<% if @user.errors[:email] %>
					<% @user.errors[:email].each do |error| %>
						<span class="help-inline text-danger">- Email <%= error %></span><br>
					<% end %>
				<% end %>
			</div>
			
			<div class="form-group">
				<%= f.label :password, class: "control-label " %>
				<%= f.password_field :password, class: "form-control" %>
				<% if @user.errors[:password] %>
					<% @user.errors[:password].each do |error| %>
						<span class="help-inline text-danger">- Password <%= error %></span><br>
					<% end %>
				<% end %>
			</div>
			
			<div class="form-group">
				<%= f.label :password_confirmation, "Confirm Password", class: "control-label" %>
				<%= f.password_field :password_confirmation, class: "form-control" %>
				<% if @user.errors[:password_confirmation] %>
					<% @user.errors[:password_confirmation].each do |error| %>
						<span class="help-inline text-danger">- Confirm Password <%= error %></span><br>
					<% end %>
				<% end %>
			</div>
			<div class="form-group">
					<%= f.submit "Save changes", class: "btn btn-large btn-primary" %>
			</div>
		<% end %>
		<%= gravatar_for @user %>
    	<a href="http://gravatar.com/emails">change</a>
	</div>
</div>

app/views/users/index.html.erb
<% provide :title, 'All users'%>
<h1>All users</h1>

<div id="users_list">
	<%= render 'users/list' %>
</div>

app/views/users/new.html.erb
<% provide :title, 'Registro'%>

<h1>Registrate</h1>
<div class="row">
	<div class="col-md-6 col-md-offset-3">
		<%= render 'shared/error_messages' %>
		<%= form_for(@user, html: { class: "", role: "form" }) do |f| %>
			<div class="form-group">
				<%= f.label :name, class: "control-label" %>
				<%= f.text_field :name, class: "form-control" %>
				<% if @user.errors[:name] %>
					<% @user.errors[:name].each do |error| %>
						<span class="help-inline text-danger">- Name <%= error %></span><br>
					<% end %>
				<% end %>
			</div>
			
			<div class="form-group">
				<%= f.label :email, class: "control-label" %>
				<%= f.text_field :email, class: "form-control" %>
				<% if @user.errors[:email] %>
					<% @user.errors[:email].each do |error| %>
						<span class="help-inline text-danger">- Email <%= error %></span><br>
					<% end %>
				<% end %>
			</div>
			
			<div class="form-group">
				<%= f.label :password, class: "control-label " %>
				<%= f.password_field :password, class: "form-control" %>
				<% if @user.errors[:password] %>
					<% @user.errors[:password].each do |error| %>
						<span class="help-inline text-danger">- Password <%= error %></span><br>
					<% end %>
				<% end %>
			</div>
			
			<div class="form-group">
				<%= f.label :password_confirmation, class: "control-label" %>
				<%= f.password_field :password_confirmation, class: "form-control" %>
				<% if @user.errors[:password_confirmation] %>
					<% @user.errors[:password_confirmation].each do |error| %>
						<span class="help-inline text-danger">- Password confirmation <%= error %></span><br>
					<% end %>
				<% end %>
			</div>
			<div class="form-group">
					<%= f.submit "Crear cuenta", class: "btn btn-large btn-primary" %>
			</div>
		<% end %>
	</div>
</div>

app/views/users/show.html.erb
<% provide(:title, @user.name) %>
<div>
  <aside>
    <section>
      <h1>
        <%= gravatar_for @user, size: 50 %>
        <%= @user.name %>
      </h1>
    </section>
  </aside>
</div>